controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true

    bzzbot_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster  
      use_sim_time: true
    bzzbot_effort_controller:
      type: effort_controllers/JointGroupEffortController
    bzzbot_diff_drive_controller:
      type: diff_drive_controller/DiffDriveController


bzzbot_effort_controller:
  ros__parameters:
    joints:
      - left_wheel_joint
      - right_wheel_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort


bzzbot_diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.30
    #wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
    wheel_radius: 0.032

    # 乘数，用于调整轮子的分离距离和半径，以适应不同的机器人平台，分别表示轮子的分离距离和半径的乘数
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_footprint
    # 机器人位姿的协方差矩阵, 用于表示机器人位姿的不确定性, 默认值为0.001, 表示0.001的不确定性
    pose_covariance_diagonal : [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]
    # 开环控制, 是否开启开环控制, 默认开启, 开启后, 机器人会根据输入的命令, 实时调整轮子的转速, 以实现运动控制
    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    #publish_limited_velocity: true
    use_stamped_vel: false
    #velocity_rolling_window_size: 10
    # 速度限制, 是否开启速度限制, 默认开启, 开启后, 机器人会根据输入的命令, 实时调整轮子的转速, 以实现运动控制
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_jerk_limits: false